name: Deploy to GKE
run-name: Deploy ${{ inputs.image_version }}

on:
  workflow_call:
    inputs:
      image_version:
        required: true
        type: string
      environment:
        required: true
        type: string

env:
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}
  GKE_NAMESPACE: ${{ secrets.GKE_NAMESPACE }}
  DEPLOYMENT_NAME: ${{ secrets.DEPLOYMENT_NAME }}
  USE_GKE_GCLOUD_AUTH_PLUGIN: true

jobs:
  build:
    uses: ./.github/workflows/docker-image.yml
    with:
      image_version: ${{inputs.image_version}}
      environment: ${{ inputs.environment }}
    secrets: inherit
  deploy:
    environment: ${{ inputs.environment }}
    name: Deploy to GKE
    runs-on: ubuntu-latest
    needs: build
    steps:
    # Deploy to GKE
    ## Setup gcloud CLI
    - uses: 'actions/checkout@v3'
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GKE_SA_KEY }}'
    - id: 'get-credentials'
      uses: 'google-github-actions/get-gke-credentials@v1'
      with:
        cluster_name: '${{ env.GKE_CLUSTER }}'
        location: '${{ env.GKE_ZONE }}'
    - uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.GKE_PROJECT }}
    - name: Install Google Auth Plugin
      run: |-
          gcloud components install gke-gcloud-auth-plugin
    ## Get the GKE credentials so we can deploy to the cluster
    - run: |-
        gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%dT%H%M%S')"
    ## Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |-
        kubectl set image deployment/$DEPLOYMENT_NAME $DEPLOYMENT_NAME=${{secrets.DOCKER_ORGANIZATION}}/${{secrets.DOCKER_REPO_NAME}}:${{inputs.image_version}} -n $GKE_NAMESPACE
        kubectl patch deployment $DEPLOYMENT_NAME --patch '{"spec": {"template": {"metadata": {"labels": {"deploy-typestamp": "${{ steps.date.outputs.date }}"}}}}}' -n $GKE_NAMESPACE
        kubectl rollout status deployment/$DEPLOYMENT_NAME -n $GKE_NAMESPACE
